name: Automate Changelog PR Title

on:
  pull_request:
    types: [opened, edited]

jobs:
  update-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate PR title from Conventional Commits
        id: generate-title
        run: |
          # Run a script to extract conventional commits and format PR title
          # Replace this with your script to generate the PR title
          # Example: Use git log command to get commit messages and generate title
          commits=$(git log --pretty=format:"%s" origin/main..HEAD)
          # Your logic to create a formatted title based on commits
          formatted_title="Your Generated Title: $commits"

          # Set the output variable for the generated title
          echo "::set-output name=title::$formatted_title"

      - name: Update Pull Request title
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = "${{ steps.generate-title.outputs.title }}";
            github.issues.update({
              issue_number: context.issue.number,
              title: title
            });
